apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: m0h77/django-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "usersdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password1!"
            - name: DB_HOST
              value: postgresql-service
            - name: DB_PORT
              value: "5432"
